backend:
  name: git-gateway
  branch: main

media_folder: "public/Productos" 
public_folder: "/Productos"

collections:
  - name: "productos"
    label: "Gestión de Productos"
    files:
      - name: "productos-list"
        label: "Todos los Productos"
        file: "src/data/products.json"
        fields:
          - label: "Productos"
            name: "products"
            widget: "list"
            summary: '{{fields.name}} - ${{fields.price}}'
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "Nombre", name: "name", widget: "string"}
              - {label: "Precio ($USD)", name: "price", widget: "number", value_type: "int"}
              - {label: "Categoría", name: "category", widget: "select", options: ["alimentos", "electronicos", "aseo"]}
              - {label: "Destacado (Top)", name: "top", widget: "boolean", default: false}
              - {label: "Descripción", name: "description", widget: "text"}
              - {label: "Imagen", name: "image", widget: "image"}
